// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-my-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's NewRestaurantsOwners profile (email, full name, restaurant name, phone).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("email, full_name, restaurant_name, phone, avatar_url, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Profile not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-pdf-resources.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.90.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
var FEATURE_SLUGS = [
  "financial-operations",
  "labor-cost-management",
  "food-cost-control",
  "employee-training",
  "essential-forms",
  "community-support"
];
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_pdf_resources_default = defineTool2({
  name: "list_pdf_resources",
  title: "List PDF resources",
  description: "List PDF resources for a feature area of NewRestaurantsOwners. Optionally filter by a tag or search text in the title/description.",
  inputSchema: {
    feature_slug: z.enum(FEATURE_SLUGS).describe("Which feature area to list PDFs for."),
    search: z.string().trim().max(100).optional().describe("Optional text to match against the PDF title or description."),
    tag: z.string().trim().max(50).optional().describe("Optional single tag to filter by (case-insensitive)."),
    limit: z.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ feature_slug, search, tag, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let query = supabase.from("feature_pdfs").select("id, title, description, tags, sort_order, created_at").eq("feature_slug", feature_slug).order("sort_order", { ascending: true }).order("created_at", { ascending: false }).limit(limit);
    if (search) {
      query = query.or(`title.ilike.%${search}%,description.ilike.%${search}%`);
    }
    if (tag) {
      query = query.contains("tags", [tag.toLowerCase()]);
    }
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: rows.length === 0 ? `No PDFs found for ${feature_slug}.` : rows.map(
            (r) => `\u2022 ${r.title}${r.description ? ` \u2014 ${r.description}` : ""}${r.tags?.length ? ` [${r.tags.join(", ")}]` : ""}`
          ).join("\n")
        }
      ],
      structuredContent: { feature_slug, count: rows.length, resources: rows }
    };
  }
});

// src/lib/mcp/tools/get-subscription-status.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.90.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_subscription_status_default = defineTool3({
  name: "get_subscription_status",
  title: "Get subscription status",
  description: "Return the signed-in user's NewRestaurantsOwners subscription status: whether they are subscribed, the tier (Starter/Professional/Enterprise), and the current period end date.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    const { data, error } = await supabase.functions.invoke("check-subscription", {
      headers: { Authorization: `Bearer ${ctx.getToken()}` }
    });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const summary = data?.subscribed ? `Subscribed to ${data.tier ?? "unknown tier"}${data.subscription_end ? ` until ${data.subscription_end}` : ""}.` : "Not currently subscribed.";
    return {
      content: [{ type: "text", text: summary }],
      structuredContent: {
        subscribed: !!data?.subscribed,
        tier: data?.tier ?? null,
        subscription_end: data?.subscription_end ?? null
      }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "spqtbqftibwuyulyegub";
var mcp_default = defineMcp({
  name: "newrestaurantsowners-mcp",
  title: "NewRestaurantsOwners MCP",
  version: "0.1.0",
  instructions: "Tools for NewRestaurantsOwners.com. Use `get_my_profile` and `get_subscription_status` to fetch the signed-in user's account context, and `list_pdf_resources` to browse operational PDF resources across the six feature areas (financial-operations, labor-cost-management, food-cost-control, employee-training, essential-forms, community-support).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_pdf_resources_default, get_subscription_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
